-- Destructive: wipes saved documents on every launch.
DROP TABLE IF EXISTS DOCUMENTS;

CREATE TABLE DOCUMENTS (
    ID        INTEGER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    URL       VARCHAR(2048) NOT NULL,
    TITLE     VARCHAR(512),
    SAVED_AT  TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONTENT   CLOB(10M)     NOT NULL
);
