CREATE TABLE IF NOT EXISTS DOCUMENTS (
    ID        INTEGER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    URL       VARCHAR(2048) NOT NULL,
    SAVED_AT  TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONTENT   CLOB(10M)     NOT NULL
);
